### ISSUE TITLE
Turning Column into LocalDate

### ISSUE THREAD

**Issue by thomasnield** [holgerbrandl/krangl#15]
I'm having an issue creating a new column that turns date text into a Java 8 `LocalDate`.

```kotlin
package com.swa.np.myproject

import krangl.*
import java.time.LocalDate
import java.time.format.DateTimeFormatter

fun main(args: Array<String>) {

    val df = DataFrame.fromCSV("C:\\Users\\e98594\\Desktop\\Iter1R1 - New Mktg Day Parameters_Inputs\\Globals\\Connection Builder_V1.csv")

    val converted = df.mutate(TableFormula("Converted EffectiveDate") {
        it["EffectiveDate"].asStrings().map { it?.substring(0,8) }.filterNotNull().map { LocalDate.parse(it, DateTimeFormatter.ofPattern("M/d/yyyy")) }
    })

    println(converted)
}
```

**ERROR:**

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at krangl.SimpleDataFrameKt.handleListErasure(SimpleDataFrame.kt:391)
	at krangl.SimpleDataFrameKt.anyAsColumn(SimpleDataFrame.kt:355)
	at krangl.SimpleDataFrame.mutate(SimpleDataFrame.kt:195)
	at com.swa.np.myproject.TestKt.main(Test.kt:16)
```

It seems to work fine if I `map()` it to anything other than a `LocalDate`. 

```kotlin
package com.swa.np.myproject

import krangl.*

fun main(args: Array<String>) {

    val df = DataFrame.fromCSV("C:\\Users\\e98594\\Desktop\\Iter1R1 - New Mktg Day Parameters_Inputs\\Globals\\Connection Builder_V1.csv")
    df.print()

    val converted = df.mutate(TableFormula("Converted EffectiveDate") {
        it["EffectiveDate"].asStrings().map { it?.substring(0,8) }
    })

    println(converted)
}

```

**Comment by thomasnield** [comment]
New example with attached CSV. Same Issue:

```kotlin
import krangl.DataFrame
import krangl.TableFormula
import krangl.asStrings
import krangl.fromCSV
import java.time.LocalDate
import java.time.format.DateTimeFormatter

fun main(args: Array<String>) {
    val df = DataFrame.fromCSV("/home/thomas/Desktop/test.txt")

    val converted = df.mutate(TableFormula("CONVERTED_SHIP_DATE") {
        it["SHIP_DATE"].asStrings()
                .map { it?.substring(0,8) }
                .filterNotNull().map { LocalDate.parse(it, DateTimeFormatter.ofPattern("M/d/yyyy")) }
    })

    println(converted)
}
```

[test.txt](https://github.com/holgerbrandl/krangl/files/926912/test.txt)

**Comment by thomasnield** [comment]
Just confirmed this is resolved. Thank you!
