### ISSUE TITLE
Joining empty DataFrame throws exception

### ISSUE THREAD

**Issue by uwemaurer** [holgerbrandl/krangl#96]
It is probably a rare edge case, but I noticed that joining an empty `DataFrame` throws a `NoSuchElementException`.

```
    val user = dataFrameOf(
            "first_name", "last_name", "age", "weight")(
            "Max", "Doe", 23, 55,
    )

    val pets = dataFrameOf("first_name", "pet")(
            "Max", "Cat",
            "Franz", "Dog",
    )
    val joinBy = listOf("first_name")

    user.filter { it["first_name"] eq "Max" }.print()
    user.filter { it["first_name"] eq "Max" }.leftJoin(pets, joinBy).print()
    user.filter { it["first_name"] eq "Max" }.outerJoin(pets, joinBy).print()

    // Hans does not exist
    user.filter { it["first_name"] eq "Hans" }.print()
    user.filter { it["first_name"] eq "Hans" }.leftJoin(pets, joinBy).print() // NoSuchElementException
    user.filter { it["first_name"] eq "Hans" }.outerJoin(pets, joinBy).print() // NoSuchElementException
```

The output is:

```
A DataFrame: 1 x 4
    first_name   last_name   age   weight
1          Max         Doe    23       55

A DataFrame: 1 x 5
    first_name   last_name   age   weight   pet
1          Max         Doe    23       55   Cat

A DataFrame: 2 x 5
    first_name   last_name    age   weight   pet
1          Max         Doe     23       55   Cat
2        Franz        <NA>   <NA>     <NA>   Dog

A DataFrame: 0 x 4
                                 first_name              last_name                    age
and 1 more variables:

Calling select() will always return an empty data-frame
Exception in thread "main" java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:212)
	at krangl.JoinsKt.join(Joins.kt:110)
	at krangl.JoinsKt.leftJoin(Joins.kt:38)
	at krangl.JoinsKt.leftJoin$default(Joins.kt:37)
```

Also calling `.print()` on the empty user DataFrame has a problem:  `and 1 more variables: Calling select() will always return an empty data-frame`

**Comment by holgerbrandl** [comment]
I always suspected that empty dataframes would cause problems with grouping. And they did, as you have pointed out correctly.  It's far from being an edge case imho: Empty arguments (in whatever shape) nicely pinpoint conceptual problems in the implementation.

Thank you for your support.

**Comment by uwemaurer** [comment]
Thank you for fixing this!
